2016-05-03 19:13:49,738 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:14:00,618 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:14:04,933 ERROR Exception on /cube/spending_2/report [GET]
Traceback (most recent call last):
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/decorators.py", line 118, in wrapper
    return f(*args, **kwargs)
  File "/Users/richardbanyi/Developer/Environments/Data/lib/python3.4/site-packages/cubes-1.1-py3.4.egg/cubes/server/blueprint.py", line 511, in cube_report
    report_request = json.loads(request.data)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
2016-05-03 19:17:51,627 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:19:50,952 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:19:53,786 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:20:05,988 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:20:06,321 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:25:33,438 ERROR Internal Cubes error (SchemaError): Unknown column 'product' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:25:39,858 ERROR Internal Cubes error (SchemaError): Unknown column 'product' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:28:57,718 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:29:00,101 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:31:01,619 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:31:03,191 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:52:08,211 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
2016-05-03 19:54:59,280 ERROR Internal Cubes error (SchemaError): Unknown column 'product_name' in table 'ft_spending_2' possible: ft_spending_2.id, ft_spending_2.transaction_type_id, ft_spending_2.date_id, ft_spending_2.product_id, ft_spending_2.geography_id, ft_spending_2.agency_id, ft_spending_2.recipient_id, ft_spending_2.award_id, ft_spending_2.award_amount, ft_spending_2.last_modified_date, ft_spending_2.date_added
